-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- Color conversion functions.
--- @class mwse.colorlib
mwse.color = {}

--- Converts given hex code in (AA)RRGGBB format to RGB(A).
--- @param rgb string No description yet available.
--- @return mwseColorTable|mwseColorATable rgb No description yet available.
function mwse.color.hexToRgb(rgb) end

--- Converts given RGB(A) color to an HTML hex code in (AA)RRGGBB format. Given color channels must be in [0, 1] range.
--- @param rgb mwseColorTable|mwseColorATable|niColor|niColorA|ffiImagePixel No description yet available.
--- @return string hex No description yet available.
function mwse.color.rgbToHex(rgb) end

