--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event fires when a particular mod's configuration menu has been closed. This happens when the MCM is closed or when a different mod's configuration menu was opened.
--- 
--- You can use this event to update your mod whenever its MCM is closed. This event may also be useful if you're trying to make your mod compatible with another mod, as it lets you detect whenever that mod updates its settings.
--- @class modConfigEntryClosedEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field isFavorite boolean *Read-only*. Whether that mod was a favorite.
--- @field modName string *Read-only*. The name of the mod that was closed.
